title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://group-a-pbl3.github.io

aux_links:
  Template Repository: https://github.com/group-a-pbl3/group-a-pbl3.github.io
