title: Group A
description: A PBL-3 project that aims to solve food waste crisis!
theme: just-the-docs

url: https://group-a-pbl3.github.io

aux_links:
  Template Repository: https://github.com/group-a-pbl3/group-a-pbl3.github.io
