title: PBL 3 - Group A
description: A PBL-3 project that aims to solve food waste crisis!
theme: just-the-docs

url: https://group-a-pbl3.github.io

aux_links:
  Main Website: https://pbl3-group-a.github.io

color_scheme: dark
